gamer_index:
    path:     /
    defaults: { _controller: "AppBundle:Gamer:index" }
    methods:  GET

gamer_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Gamer:show" }
    methods:  GET

gamer_new:
    path:     /new
    defaults: { _controller: "AppBundle:Gamer:new" }
    methods:  [GET, POST]

gamer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Gamer:edit" }
    methods:  [GET, POST]

gamer_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Gamer:delete" }
    methods:  DELETE
